import { useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import { Activity, Bot, CircleAlert, Database, FileCheck2, MessageSquareText, UsersRound } from "lucide-react";
import { useTranslation } from "react-i18next";
import toast from "react-hot-toast";
import { analyticsService, type AnalyticsOverview, type RankedMetric } from "../services/analyticsService";

export default function AnalyticsPage() {
  const { i18n } = useTranslation(); const fa = i18n.language.startsWith("fa"); const [days, setDays] = useState<7 | 30 | 90>(30); const [data, setData] = useState<AnalyticsOverview | null>(null); const [loading, setLoading] = useState(true);
  useEffect(() => { setLoading(true); analyticsService.overview(days).then(setData).catch((e) => toast.error(e.message)).finally(() => setLoading(false)); }, [days]);
  const c = fa ? { eyebrow: "بینش‌های محصول", title: "تحلیل فضای کاری", subtitle: "کیفیت پاسخ، میزان استفاده و سلامت منابع را با داده واقعی دنبال کنید.", queries: "کل پرسش‌ها", users: "کاربران فعال", grounded: "پاسخ‌های مستند", satisfaction: "رضایت ثبت‌شده", noFeedback: "بدون بازخورد", coverage: "پوشش بازخورد", unanswered: "بدون مدرک", citations: "میانگین ارجاع", docs: "اسناد آماده", trend: "روند پرسش‌ها", trendSub: "پرسش‌ها و پاسخ‌های مستند در طول زمان", assistants: "عملکرد دستیارها", sets: "عملکرد مجموعه‌ها", reasons: "دلایل بازخورد منفی", issues: "خطاهای نیازمند توجه", empty: "هنوز داده‌ای در این بازه وجود ندارد", query: "پرسش", positive: "رضایت", groundedLabel: "مستند" } : { eyebrow: "Product insights", title: "Workspace analytics", subtitle: "Track answer quality, adoption, and source health with real usage data.", queries: "Total queries", users: "Active users", grounded: "Grounded answers", satisfaction: "Recorded satisfaction", noFeedback: "No feedback", coverage: "Feedback coverage", unanswered: "Without evidence", citations: "Avg. citations", docs: "Ready documents", trend: "Query trend", trendSub: "Questions and grounded answers over time", assistants: "Assistant performance", sets: "Knowledge set performance", reasons: "Negative feedback reasons", issues: "Issues needing attention", empty: "No data is available for this period yet", query: "queries", positive: "satisfaction", groundedLabel: "grounded" };
  const maxQueries = useMemo(() => Math.max(1, ...(data?.daily.map((x) => x.queries) || [1])), [data]);
  if (loading && !data) return <div className="grid h-full place-items-center"><span className="size-6 animate-spin rounded-full border-2 border-white/10 border-t-[#a995eb]" /></div>;
  return <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} className="h-full overflow-y-auto px-4 py-5 scrollbar-thin scrollbar-thumb-white/10 sm:px-6 lg:px-8"><div className="mx-auto w-full max-w-[1180px] pb-8"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><div className="mb-2 flex items-center gap-2 text-[11px] font-bold uppercase tracking-[.2em] text-[#a995eb]"><span className="size-1.5 rounded-full bg-[#8f78d8]" />{c.eyebrow}</div><h1 className="text-3xl font-semibold tracking-[-.045em] sm:text-4xl">{c.title}</h1><p className="mt-2 text-sm text-white/35">{c.subtitle}</p></div><div className="flex rounded-xl border border-white/[.08] bg-white/[.025] p-1">{([7, 30, 90] as const).map((value) => <button key={value} onClick={() => setDays(value)} className={`rounded-lg px-3 py-2 text-[10px] font-semibold transition ${days === value ? "bg-[#32127A] text-white" : "text-white/35 hover:text-white/60"}`}>{fa ? `${value} روز` : `${value} days`}</button>)}</div></header>
    {data && <><section className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric icon={MessageSquareText} label={c.queries} value={data.total_queries.toLocaleString()} detail={`${data.unanswered_queries} ${c.unanswered}`} /><Metric icon={UsersRound} label={c.users} value={data.active_users.toLocaleString()} detail={`${data.feedback_coverage}% ${c.coverage}`} /><Metric icon={FileCheck2} label={c.grounded} value={`${data.grounded_rate}%`} detail={`${data.average_citations} ${c.citations}`} /><Metric icon={Activity} label={c.satisfaction} value={data.positive_feedback_rate == null ? "—" : `${data.positive_feedback_rate}%`} detail={data.positive_feedback_rate == null ? c.noFeedback : `${data.feedback_coverage}% ${c.coverage}`} /></section>
    <section className="mt-3 grid gap-3 lg:grid-cols-[minmax(0,1.7fr)_minmax(280px,.8fr)]"><div className="app-glass-panel rounded-[22px] p-5"><div><h2 className="text-sm font-semibold">{c.trend}</h2><p className="mt-1 text-[10px] text-white/25">{c.trendSub}</p></div><div className="mt-6 flex h-44 items-end gap-1 sm:gap-2">{data.daily.map((item, index) => <div key={item.date} className="group relative flex h-full min-w-0 flex-1 items-end"><div className="relative w-full rounded-t-md bg-[#32127A]/30 transition group-hover:bg-[#32127A]/50" style={{ height: `${Math.max(item.queries ? 5 : 1, item.queries / maxQueries * 100)}%` }}><div className="absolute inset-x-0 bottom-0 rounded-t-md bg-gradient-to-t from-[#6f52c5] to-[#9b86e1]" style={{ height: `${item.queries ? item.grounded / item.queries * 100 : 0}%` }} /></div>{(index === 0 || index === data.daily.length - 1 || (data.daily.length <= 7)) && <span className="absolute top-full mt-2 text-[8px] text-white/20">{new Date(item.date).toLocaleDateString(fa ? "fa-IR" : "en", { month: "short", day: "numeric" })}</span>}<div className="pointer-events-none absolute bottom-full start-1/2 z-10 mb-2 hidden -translate-x-1/2 rounded-lg border border-white/10 bg-[#15111d] px-2 py-1 text-[9px] whitespace-nowrap shadow-xl group-hover:block">{item.queries} {c.query} · {item.grounded} {c.groundedLabel}</div></div>)}</div></div><div className="app-glass-panel rounded-[22px] p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">{c.docs}</h2><Database size={16} className="text-[#a995eb]" /></div><div className="mt-6 flex items-end gap-2"><span className="text-4xl font-semibold tracking-[-.05em]">{data.indexed_documents}</span><span className="mb-1 text-xs text-white/25">indexed</span></div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-white/[.06]"><div className="h-full rounded-full bg-gradient-to-r from-[#32127A] to-[#a995eb]" style={{ width: `${data.indexed_documents + data.failed_documents ? data.indexed_documents / (data.indexed_documents + data.failed_documents) * 100 : 0}%` }} /></div><p className={`mt-3 text-[10px] ${data.failed_documents ? "text-rose-200/50" : "text-emerald-200/45"}`}>{data.failed_documents} failed documents</p></div></section>
    <section className="mt-3 grid gap-3 lg:grid-cols-2"><Ranking title={c.assistants} icon={Bot} items={data.assistants} copy={c} /><Ranking title={c.sets} icon={Database} items={data.knowledge_sets} copy={c} /></section>
    <section className="mt-3 grid gap-3 lg:grid-cols-2"><div className="app-glass-panel rounded-[22px] p-5"><h2 className="text-sm font-semibold">{c.reasons}</h2><div className="mt-4 space-y-3">{data.negative_reasons.length ? data.negative_reasons.map((item) => { const total = data.negative_reasons.reduce((sum, x) => sum + x.count, 0); return <div key={item.reason}><div className="mb-1.5 flex justify-between text-[10px]"><span className="text-white/45">{reasonLabel(item.reason, fa)}</span><span className="text-white/25">{item.count}</span></div><div className="h-1.5 rounded-full bg-white/[.05]"><div className="h-full rounded-full bg-rose-300/45" style={{ width: `${item.count / total * 100}%` }} /></div></div>}) : <Empty text={c.empty} />}</div></div><div className="app-glass-panel rounded-[22px] p-5"><h2 className="text-sm font-semibold">{c.issues}</h2><div className="mt-4 space-y-2">{data.recent_issues.length ? data.recent_issues.map((item, index) => <div key={`${item.name}-${index}`} className="flex gap-3 rounded-xl border border-white/[.055] bg-white/[.02] p-3"><CircleAlert size={14} className="mt-0.5 shrink-0 text-rose-200/50" /><div className="min-w-0"><p className="truncate text-[11px] font-semibold text-white/60">{item.name}</p><p className="mt-1 line-clamp-2 text-[9px] leading-4 text-white/25">{item.detail}</p></div></div>) : <Empty text={c.empty} />}</div></div></section></>}
  </div></motion.div>;
}

function Metric({ icon: Icon, label, value, detail }: { icon: typeof Activity; label: string; value: string; detail: string }) { return <div className="app-glass-panel rounded-[20px] p-4"><div className="flex items-center justify-between"><span className="text-[10px] font-semibold uppercase tracking-[.12em] text-white/30">{label}</span><span className="grid size-8 place-items-center rounded-xl bg-[#32127A]/20 text-[#a995eb]"><Icon size={14} /></span></div><p className="mt-4 text-3xl font-semibold tracking-[-.05em]">{value}</p><p className="mt-2 text-[9px] text-white/20">{detail}</p></div>; }
function Ranking({ title, icon: Icon, items, copy }: { title: string; icon: typeof Bot; items: RankedMetric[]; copy: Record<string, string> }) { const max = Math.max(1, ...items.map((x) => x.queries)); return <div className="app-glass-panel rounded-[22px] p-5"><div className="flex items-center justify-between"><h2 className="text-sm font-semibold">{title}</h2><Icon size={16} className="text-[#a995eb]" /></div><div className="mt-4 space-y-3">{items.length ? items.map((item) => <div key={item.id || item.name}><div className="mb-1.5 flex items-center justify-between gap-3"><span className="truncate text-[11px] text-white/55">{item.name}</span><span className="shrink-0 text-[9px] text-white/25">{item.queries} {copy.query} · {item.grounded_rate}% {copy.groundedLabel}{item.positive_rate != null ? ` · ${item.positive_rate}% ${copy.positive}` : ""}</span></div><div className="h-1.5 rounded-full bg-white/[.05]"><div className="h-full rounded-full bg-gradient-to-r from-[#32127A] to-[#8f78d8]" style={{ width: `${item.queries / max * 100}%` }} /></div></div>) : <Empty text={copy.empty} />}</div></div>; }
function Empty({ text }: { text: string }) { return <div className="grid min-h-24 place-items-center text-[10px] text-white/20">{text}</div>; }
function reasonLabel(reason: string, fa: boolean) { const labels: Record<string, [string, string]> = { incorrect: ["Incorrect answer", "پاسخ اشتباه"], irrelevant_source: ["Irrelevant source", "منبع نامرتبط"], incomplete: ["Incomplete answer", "پاسخ ناقص"], citation_issue: ["Citation issue", "مشکل ارجاع"], other: ["Other", "سایر"] }; return labels[reason]?.[fa ? 1 : 0] || reason; }
