import { useEffect, useState } from "react";
import { FileText, LockKeyhole, MessageSquareText, Sparkles } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { authService } from "../services/authService";
import { shareService, type SharedChat } from "../services/shareService";
import AnswerTrustBadge from "../components/AnswerTrustBadge";
import "../styles/chat-answer.css";

export default function SharedChatPage() {
  const { visibility, token } = useParams(); const mode = visibility === "team" ? "team" : "link"; const [data, setData] = useState<SharedChat | null>(null); const [error, setError] = useState("");
  useEffect(() => { if (!token) return; shareService.view(token, mode).then(setData).catch((e) => setError(e.message)); }, [mode, token]);
  if (mode === "team" && !authService.isAuthenticated()) return <div className="grid min-h-[100dvh] place-items-center bg-[#070d20] p-5 text-white"><div className="app-glass-panel w-full max-w-sm rounded-[24px] p-7 text-center"><LockKeyhole className="mx-auto text-[#c43cff]" /><h1 className="mt-4 text-xl font-semibold">Team-only conversation</h1><p className="mt-2 text-xs leading-5 text-white/35">Sign in to your workspace to view this shared conversation.</p><Link to="/" className="mt-6 block rounded-xl bg-[#7c27ff] py-3 text-xs font-semibold">Sign in</Link></div></div>;
  return <div className="min-h-[100dvh] bg-[#070d20] px-4 py-8 text-white sm:px-6"><div className="pointer-events-none fixed inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(124,39,255,.25),transparent_45%)]" /><main className="relative mx-auto max-w-3xl"><header className="app-glass-panel rounded-[24px] p-5 sm:p-6"><div className="flex items-center gap-3"><span className="grid size-11 place-items-center rounded-2xl bg-[#7c27ff]/30 text-[#d9a6ff]"><MessageSquareText size={19} /></span><div className="min-w-0"><h1 className="truncate text-lg font-semibold">{data?.title || "Shared conversation"}</h1><p className="mt-1 text-xs text-white/30">{data ? `Shared by ${data.owner_username} · ${new Date(data.created_at).toLocaleDateString()}` : "Loading secure snapshot…"}</p></div></div></header>{error && <div className="mt-4 rounded-2xl border border-rose-300/10 bg-rose-300/[.04] p-5 text-center text-xs text-rose-200/60">{error}</div>}<section className="mt-4 space-y-4">{data?.messages.map((message, index) => <article key={index} className={`flex gap-3 ${message.role === "user" ? "justify-end" : "justify-start"}`}>{message.role === "assistant" && <span className="mt-1 grid size-8 shrink-0 place-items-center rounded-xl bg-[#7c27ff]/25 text-[#c43cff]"><Sparkles size={14} /></span>}<div className={`max-w-[85%] rounded-2xl px-4 py-3 text-sm leading-6 ${message.role === "user" ? "rounded-br-md bg-[#7c27ff]" : "rounded-tl-md border border-white/[.08] bg-white/[.04] text-white/75"}`}><p className="whitespace-pre-wrap">{message.content}</p>{message.role === "assistant" && <AnswerTrustBadge compact answerBasis={message.answer_basis} grounded={message.grounded} sourceCount={message.sources.length} isFa={false} />}{message.sources.length > 0 && <div className="mt-3 flex flex-wrap gap-2 border-t border-white/[.07] pt-3">{message.sources.map((source, sourceIndex) => <span key={sourceIndex} title={source.excerpt} className="flex items-center gap-1.5 rounded-lg border border-white/[.07] bg-black/15 px-2.5 py-1.5 text-xs text-white/40"><FileText size={11} />{source.citation_id && <span className="text-[#c43cff]">[{source.citation_id}]</span>}{source.title}</span>)}</div>}</div></article>)}</section><footer className="mt-8 text-center text-xs text-white/20">Read-only conversation snapshot · Nexora</footer></main></div>;
}


