import { useEffect, useState } from "react";
import { Database, Play, Plus, Trash2, X } from "lucide-react";
import toast from "react-hot-toast";
import { knowledgeService, type EvaluationCase, type MetadataFilters, type PipelineTraceResponse } from "../services/knowledgeService";

type Props = { setId: string; documentIds: string[]; filters: MetadataFilters; isFa: boolean; canManage: boolean; onClose: () => void };

export default function EvaluationDataset({ setId, documentIds, filters, isFa, canManage, onClose }: Props) {
  const [cases, setCases] = useState<EvaluationCase[]>([]); const [loading, setLoading] = useState(true); const [adding, setAdding] = useState(false);
  const [question, setQuestion] = useState(""); const [answer, setAnswer] = useState(""); const [keywords, setKeywords] = useState("");
  const [running, setRunning] = useState<string | null>(null); const [results, setResults] = useState<Record<string, PipelineTraceResponse>>({});
  const load = () => knowledgeService.listEvaluationCases(setId).then(setCases).catch((error) => toast.error((error as Error).message)).finally(() => setLoading(false));
  useEffect(() => { void load(); }, [setId]);
  const create = async () => { if (question.trim().length < 2) return; try { const item = await knowledgeService.createEvaluationCase(setId, { question: question.trim(), expected_answer: answer.trim() || null, expected_keywords: keywords.split(",").map((value) => value.trim()).filter(Boolean) }); setCases((items) => [item, ...items]); setQuestion(""); setAnswer(""); setKeywords(""); setAdding(false); } catch (error) { toast.error((error as Error).message); } };
  const run = async (item: EvaluationCase) => { setRunning(item.id); try { const result = await knowledgeService.tracePipeline(item.question, setId, 5, documentIds, filters); setResults((values) => ({ ...values, [item.id]: result })); } catch (error) { toast.error((error as Error).message); } finally { setRunning(null); } };

  return <div className="fixed inset-0 z-[98] flex justify-end bg-black/75 backdrop-blur-md" onMouseDown={onClose}><aside onMouseDown={(event) => event.stopPropagation()} className="flex h-full w-full max-w-2xl flex-col border-s border-white/10 bg-[rgba(10,8,15,.99)]"><header className="flex h-20 shrink-0 items-center justify-between border-b border-white/[.08] px-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#32127A]/30 text-[#b6a7ef]"><Database size={18} /></span><div><h2 className="text-sm font-semibold">Evaluation Dataset</h2><p className="mt-1 text-[10px] text-white/30">{cases.length} {isFa ? "سناریوی ارزیابی" : "evaluation cases"}</p></div></div><div className="flex gap-2">{canManage && <button onClick={() => setAdding((value) => !value)} className="app-icon-button grid size-9 place-items-center rounded-xl text-[#b6a7ef]"><Plus size={16} /></button>}<button onClick={onClose} className="app-icon-button grid size-9 place-items-center rounded-xl"><X size={16} /></button></div></header>
    {adding && <div className="shrink-0 space-y-3 border-b border-white/[.07] p-4"><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder={isFa ? "سؤال مرجع" : "Reference question"} className="h-10 w-full rounded-xl border border-white/[.08] bg-white/[.035] px-3 text-xs outline-none" /><textarea value={answer} onChange={(event) => setAnswer(event.target.value)} placeholder={isFa ? "پاسخ مورد انتظار (اختیاری)" : "Expected answer (optional)"} className="min-h-20 w-full resize-y rounded-xl border border-white/[.08] bg-white/[.035] p-3 text-xs outline-none" /><input value={keywords} onChange={(event) => setKeywords(event.target.value)} placeholder={isFa ? "Keywordهای الزامی، جداشده با کاما" : "Required keywords, comma separated"} className="h-10 w-full rounded-xl border border-white/[.08] bg-white/[.035] px-3 text-xs outline-none" /><div className="flex justify-end"><button onClick={() => void create()} className="rounded-xl bg-[#32127A] px-4 py-2.5 text-[10px] font-semibold">{isFa ? "افزودن Case" : "Add case"}</button></div></div>}
    <div className="min-h-0 flex-1 overflow-y-auto p-4">{loading ? <div className="grid min-h-48 place-items-center"><span className="size-5 animate-spin rounded-full border-2 border-white/10 border-t-[#a995eb]" /></div> : cases.map((item) => { const result = results[item.id]; const answerLower = result?.answer.toLocaleLowerCase() || ""; const matched = item.expected_keywords.filter((keyword) => answerLower.includes(keyword.toLocaleLowerCase())).length; const coverage = item.expected_keywords.length ? Math.round(matched / item.expected_keywords.length * 100) : null; return <article key={item.id} className="mb-3 rounded-2xl border border-white/[.08] bg-white/[.025] p-4"><div className="flex items-start gap-3"><div className="min-w-0 flex-1"><p className="text-xs font-semibold leading-5 text-white/70">{item.question}</p>{item.expected_keywords.length > 0 && <div className="mt-2 flex flex-wrap gap-1">{item.expected_keywords.map((keyword) => <span key={keyword} className="rounded-md bg-[#32127A]/20 px-2 py-1 text-[8px] text-[#c5b8f4]/70">{keyword}</span>)}</div>}</div><button disabled={running === item.id} onClick={() => void run(item)} className="app-icon-button grid size-8 shrink-0 place-items-center rounded-lg text-[#b6a7ef]"><Play size={12} /></button>{canManage && <button onClick={async () => { await knowledgeService.deleteEvaluationCase(setId, item.id); setCases((values) => values.filter((value) => value.id !== item.id)); }} className="app-icon-button grid size-8 shrink-0 place-items-center rounded-lg text-white/20 hover:text-rose-300"><Trash2 size={12} /></button>}</div>{result && <div className="mt-3 rounded-xl border border-white/[.06] bg-black/20 p-3"><div className="flex flex-wrap gap-3 text-[9px]"><span className={result.grounded ? "text-emerald-300/65" : "text-amber-300/65"}>{result.grounded ? "Grounded" : "Ungrounded"}</span><span className="text-white/30">{result.citations.length} citations</span><span className="text-white/30">{result.total_duration_ms} ms</span>{coverage !== null && <span className={coverage >= 70 ? "text-emerald-300/65" : "text-amber-300/65"}>Keyword coverage: {coverage}%</span>}</div><p className="mt-3 line-clamp-4 whitespace-pre-wrap text-[10px] leading-5 text-white/40">{result.answer}</p></div>}</article>; })}{!loading && !cases.length && <div className="grid min-h-56 place-items-center text-center text-xs text-white/25">{isFa ? "هنوز Case ارزیابی ثبت نشده است." : "No evaluation cases yet."}</div>}</div>
  </aside></div>;
}
