import { useState } from "react";
import { GitCompareArrows, Play, X } from "lucide-react";
import toast from "react-hot-toast";
import { knowledgeService, type MetadataFilters, type RetrieverComparison as Comparison, type RetrieverConfig } from "../services/knowledgeService";

type Props = { setId: string; query: string; documentIds: string[]; filters: MetadataFilters; isFa: boolean; onClose: () => void };
const initialA: RetrieverConfig = { name: "Balanced", vector_weight: 1, bm25_weight: 1, use_reranker: true, top_k: 5 };
const initialB: RetrieverConfig = { name: "Vector-heavy", vector_weight: 2, bm25_weight: .5, use_reranker: true, top_k: 5 };

export default function RetrieverComparison({ setId, query: initialQuery, documentIds, filters, isFa, onClose }: Props) {
  const [query, setQuery] = useState(initialQuery); const [a, setA] = useState(initialA); const [b, setB] = useState(initialB); const [data, setData] = useState<Comparison | null>(null); const [loading, setLoading] = useState(false);
  const run = async () => { if (query.trim().length < 2) return; setLoading(true); try { setData(await knowledgeService.compareRetrievers(query.trim(), setId, a, b, documentIds, filters)); } catch (error) { toast.error((error as Error).message); } finally { setLoading(false); } };
  return <div className="absolute inset-0 z-20 flex flex-col bg-[rgba(10,8,15,.995)]"><header className="flex h-20 shrink-0 items-center justify-between border-b border-white/[.08] px-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#7c27ff]/30 text-[#d9a6ff]"><GitCompareArrows size={18} /></span><div><h2 className="text-sm font-semibold">{isFa ? "مقایسهٔ Retriever" : "Retriever A/B Comparison"}</h2><p className="mt-1 text-xs text-white/45">Same question · same scope · independent pipelines</p></div></div><button onClick={onClose} className="app-icon-button grid size-9 place-items-center rounded-xl"><X size={16} /></button></header><div className="flex shrink-0 gap-2 border-b border-white/[.07] p-4"><input value={query} onChange={(event) => setQuery(event.target.value)} className="h-10 min-w-0 flex-1 rounded-xl border border-white/[.08] bg-white/[.035] px-3 text-xs outline-none" /><button disabled={loading || query.trim().length < 2} onClick={() => void run()} className="flex h-10 items-center gap-2 rounded-xl bg-[#7c27ff] px-4 text-xs font-semibold disabled:opacity-40"><Play size={12} />{loading ? "…" : isFa ? "مقایسه" : "Compare"}</button></div><div className="grid min-h-0 flex-1 overflow-y-auto md:grid-cols-2 md:overflow-hidden"><Variant config={a} onChange={setA} result={data?.variant_a} other={data?.variant_b} isFa={isFa} /><Variant config={b} onChange={setB} result={data?.variant_b} other={data?.variant_a} isFa={isFa} right /></div>{data && <footer className="shrink-0 border-t border-white/[.07] p-3 text-center text-xs text-white/45">{data.overlap_count} shared results · {Object.values(data.rank_changes).filter((value) => value !== 0).length} rank changes</footer>}</div>;
}

function Variant({ config, onChange, result, other, isFa, right }: { config: RetrieverConfig; onChange: (value: RetrieverConfig) => void; result?: Comparison["variant_a"]; other?: Comparison["variant_a"]; isFa: boolean; right?: boolean }) {
  return <section className={`min-h-0 overflow-y-auto p-4 ${right ? "border-t border-white/[.07] md:border-s md:border-t-0" : ""}`}><input value={config.name} onChange={(event) => onChange({ ...config, name: event.target.value })} className="h-9 w-full rounded-xl border border-white/[.08] bg-white/[.03] px-3 text-xs font-semibold outline-none" /><div className="mt-3 grid grid-cols-3 gap-2"><NumberField label="Vector" value={config.vector_weight} step={.1} onChange={(value) => onChange({ ...config, vector_weight: value })} /><NumberField label="BM25" value={config.bm25_weight} step={.1} onChange={(value) => onChange({ ...config, bm25_weight: value })} /><NumberField label="Top K" value={config.top_k} step={1} onChange={(value) => onChange({ ...config, top_k: value })} /></div><label className="mt-3 flex items-center justify-between rounded-xl border border-white/[.06] bg-white/[.02] p-3 text-xs text-white/55">Reranker<input type="checkbox" checked={config.use_reranker} onChange={(event) => onChange({ ...config, use_reranker: event.target.checked })} className="accent-[#7c27ff]" /></label>{result && <><div className="mt-4 grid grid-cols-3 gap-2">{[["Latency", `${result.duration_ms}ms`], ["Grounded", result.grounded ? "Yes" : "No"], ["Citations", result.citations.length]].map(([label, value]) => <div key={label} className="rounded-xl bg-black/20 p-2"><p className="text-xs text-white/45">{label}</p><p className="mt-1 text-xs text-white/65">{value}</p></div>)}</div><div className="mt-3 space-y-2">{result.results.map((item, index) => { const otherRank = other?.results.findIndex((value) => value.chunk_id === item.chunk_id) ?? -1; return <div key={item.chunk_id} className="rounded-xl border border-white/[.06] bg-white/[.02] p-3"><div className="flex justify-between gap-2"><span className="truncate text-xs text-white/65">#{index + 1} · {item.filename}</span><span className={`text-xs ${otherRank < 0 ? "text-amber-300/70" : otherRank + 1 === index + 1 ? "text-white/45" : "text-[#d9a6ff]"}`}>{otherRank < 0 ? "unique" : `Δ ${(otherRank + 1) - (index + 1)}`}</span></div><p className="mt-2 line-clamp-2 text-xs leading-5 text-white/45">{item.matched_child_content}</p></div>; })}</div><div className="mt-3 rounded-xl border border-[#18c7f4]/12 bg-[#7c27ff]/10 p-3"><p className="mb-2 text-xs uppercase text-[#d9a6ff]">{isFa ? "پاسخ" : "Answer"}</p><p className="whitespace-pre-wrap text-xs leading-6 text-white/60">{result.answer}</p></div></>}</section>;
}

function NumberField({ label, value, step, onChange }: { label: string; value: number; step: number; onChange: (value: number) => void }) { return <label className="text-xs text-white/45">{label}<input type="number" min={0} max={label === "Top K" ? 8 : 3} step={step} value={value} onChange={(event) => onChange(Number(event.target.value))} className="mt-1 h-9 w-full rounded-lg border border-white/[.07] bg-black/20 px-2 text-xs text-white/65 outline-none" /></label>; }

