import { useState } from "react";
import { ArrowDown, Bot, Database, FlaskConical, GitCompareArrows, ListFilter, Search, Sparkles, X } from "lucide-react";
import toast from "react-hot-toast";
import { knowledgeService, type MetadataFilters, type PipelineTraceResponse } from "../services/knowledgeService";
import EvaluationDataset from "./EvaluationDataset";
import RetrieverComparison from "./RetrieverComparison";

type Props = { setId: string; documentIds: string[]; filters: MetadataFilters; isFa: boolean; canManage: boolean; onClose: () => void };
const icons = { question: Search, retrieval: ListFilter, rerank: Sparkles, answer: Bot };

export default function RetrievalPlayground({ setId, documentIds, filters, isFa, canManage, onClose }: Props) {
  const [query, setQuery] = useState("");
  const [limit, setLimit] = useState(5);
  const [loading, setLoading] = useState(false);
  const [trace, setTrace] = useState<PipelineTraceResponse | null>(null);
  const [datasetOpen, setDatasetOpen] = useState(false);
  const [comparisonOpen, setComparisonOpen] = useState(false);
  const run = async () => { if (query.trim().length < 2) return; setLoading(true); try { setTrace(await knowledgeService.tracePipeline(query.trim(), setId, limit, documentIds, filters)); } catch (error) { toast.error((error as Error).message); } finally { setLoading(false); } };

  const labels = isFa ? { title: "ردیابی کامل RAG", sub: "سؤال ← بازیابی ← بازرتبه‌بندی ← پاسخ", placeholder: "یک سؤال آزمایشی وارد کنید", run: "اجرای کامل", total: "زمان کل", grounded: "پاسخ مستند", ungrounded: "بدون استناد", empty: "یک سؤال اجرا کنید تا مسیر کامل تصمیم‌گیری سیستم نمایش داده شود.", question: "سؤال", retrieval: "بازیابی", rerank: "بازرتبه‌بندی", answer: "پاسخ" } : { title: "Full RAG Trace", sub: "Question → Retrieval → Rerank → Answer", placeholder: "Enter a test question", run: "Run pipeline", total: "Total time", grounded: "Grounded", ungrounded: "Ungrounded", empty: "Run a question to inspect the complete decision path.", question: "Question", retrieval: "Retrieval", rerank: "Rerank", answer: "Answer" };

  return <div className="fixed inset-0 z-[95] flex justify-end bg-black/70 backdrop-blur-sm" onMouseDown={onClose}><aside onMouseDown={(event) => event.stopPropagation()} className="relative flex h-full w-full max-w-4xl flex-col border-s border-white/10 bg-[rgba(10,8,15,.98)] shadow-2xl"><div className="absolute end-16 top-[22px] z-10 flex gap-2"><button onClick={() => setComparisonOpen(true)} className="flex h-9 items-center gap-2 rounded-xl border border-white/[.08] bg-white/[.03] px-3 text-[9px] text-white/40 hover:text-[#b6a7ef]"><GitCompareArrows size={13} /><span className="hidden sm:inline">A/B</span></button><button onClick={() => setDatasetOpen(true)} className="flex h-9 items-center gap-2 rounded-xl border border-white/[.08] bg-white/[.03] px-3 text-[9px] text-white/40 hover:text-[#b6a7ef]"><Database size={13} /><span className="hidden sm:inline">Dataset</span></button></div>
    <header className="flex h-20 shrink-0 items-center justify-between border-b border-white/[.08] px-5"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-[#32127A]/30 text-[#b6a7ef]"><FlaskConical size={18} /></span><div><h2 className="text-sm font-semibold">{labels.title}</h2><p className="mt-1 text-[10px] text-white/30">{labels.sub}</p></div></div><button onClick={onClose} className="app-icon-button grid size-9 place-items-center rounded-xl"><X size={16} /></button></header>
    <div className="flex shrink-0 gap-2 border-b border-white/[.07] p-4"><label className="relative min-w-0 flex-1"><Search size={14} className="absolute start-3 top-1/2 -translate-y-1/2 text-white/25" /><input value={query} onChange={(event) => setQuery(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void run(); }} placeholder={labels.placeholder} className="h-11 w-full rounded-xl border border-white/10 bg-white/[.04] ps-9 pe-3 text-sm outline-none focus:border-[#8f78d8]/40" /></label><select value={limit} onChange={(event) => setLimit(Number(event.target.value))} className="rounded-xl border border-white/10 bg-[#100e15] px-3 text-xs">{[3, 5, 8].map((value) => <option key={value} value={value}>Top {value}</option>)}</select><button disabled={loading || query.trim().length < 2} onClick={() => void run()} className="rounded-xl bg-[#32127A] px-4 text-xs font-semibold disabled:opacity-40 sm:px-5">{loading ? "…" : labels.run}</button></div>
    <div className="min-h-0 flex-1 overflow-y-auto p-4 sm:p-5">{!trace ? <div className="grid min-h-72 place-items-center text-center"><div><FlaskConical className="mx-auto text-white/15" size={32} /><p className="mt-4 text-xs text-white/30">{labels.empty}</p></div></div> : <>
      <div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><p className="text-[10px] text-white/25">{labels.total}</p><p className="mt-1 text-lg font-semibold text-white/75">{trace.total_duration_ms.toLocaleString()} ms</p></div><span className={`rounded-full border px-3 py-1.5 text-[10px] ${trace.grounded ? "border-emerald-300/15 bg-emerald-300/[.05] text-emerald-200/65" : "border-amber-300/15 bg-amber-300/[.05] text-amber-200/65"}`}>{trace.grounded ? labels.grounded : labels.ungrounded}</span></div>
      <div className="grid gap-2 sm:grid-cols-4">{trace.stages.map((stage, index) => { const Icon = icons[stage.key]; return <div key={stage.key} className="relative rounded-2xl border border-white/[.08] bg-white/[.025] p-4">{index < trace.stages.length - 1 && <ArrowDown size={12} className="absolute -bottom-3 left-1/2 z-10 -translate-x-1/2 text-[#8f78d8] sm:-right-3 sm:bottom-auto sm:left-auto sm:top-1/2 sm:-translate-y-1/2 sm:-rotate-90" />}<div className="flex items-center justify-between"><span className="grid size-8 place-items-center rounded-lg bg-[#32127A]/25 text-[#b6a7ef]"><Icon size={14} /></span><span className="text-[9px] text-white/25">{stage.duration_ms} ms</span></div><p className="mt-3 text-[11px] font-semibold text-white/65">{labels[stage.key]}</p><p className="mt-1 text-[9px] text-white/25">{stage.input_count} in → {stage.output_count} out</p></div>; })}</div>
      <section className="mt-5 rounded-2xl border border-white/[.08] bg-white/[.02] p-4"><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-white/25">01 · {labels.question}</p><p className="mt-3 text-sm leading-6 text-white/70">{trace.question}</p></section>
      <section className="mt-3 rounded-2xl border border-white/[.08] bg-white/[.02] p-4"><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-white/25">02–03 · {labels.retrieval} + {labels.rerank}</p><div className="mt-3 space-y-2">{trace.results.map((item, index) => <details key={`${item.chunk_id}-${index}`} className="rounded-xl border border-white/[.06] bg-black/15 p-3"><summary className="flex cursor-pointer list-none items-center justify-between gap-3"><span className="min-w-0 truncate text-[10px] font-semibold text-white/55">#{index + 1} · {item.filename} · Child {item.chunk_index + 1}</span><span className="shrink-0 rounded-lg bg-[#32127A]/25 px-2 py-1 text-[9px] text-[#c5b8f4]">{Math.round(item.score * 100)}%</span></summary><div className="mt-3 grid grid-cols-3 gap-2">{[["Vector", item.diagnostics.vector_rank ?? "—"], ["BM25", item.diagnostics.bm25_rank ?? "—"], ["Rerank", item.diagnostics.reranker_score.toFixed(3)]].map(([name, value]) => <div key={name} className="rounded-lg bg-white/[.025] p-2"><p className="text-[8px] text-white/20">{name}</p><p className="mt-1 text-[9px] text-white/50">{value}</p></div>)}</div><p className="mt-3 whitespace-pre-wrap text-[10px] leading-5 text-white/35">{item.matched_child_content}</p></details>)}</div></section>
      <section className="mt-3 rounded-2xl border border-[#8f78d8]/15 bg-[#32127A]/10 p-4"><div className="flex items-center justify-between"><p className="text-[9px] font-semibold uppercase tracking-[.14em] text-[#b6a7ef]">04 · {labels.answer}</p><span className="text-[9px] text-white/25">{trace.citations.length} citations</span></div><p className="mt-3 whitespace-pre-wrap text-sm leading-7 text-white/70">{trace.answer}</p>{trace.citations.length > 0 && <div className="mt-4 flex flex-wrap gap-2 border-t border-white/[.07] pt-3">{trace.citations.map((citation) => <span key={citation.id} className="rounded-lg border border-white/[.07] bg-black/15 px-2.5 py-1.5 text-[9px] text-white/40">[{citation.id}] {citation.filename}</span>)}</div>}</section>
      {trace.usage && <section className="mt-3 grid grid-cols-2 gap-2 rounded-2xl border border-white/[.07] bg-white/[.02] p-3 sm:grid-cols-5">{[["Model", trace.usage.model], ["LLM latency", `${trace.usage.latency_ms} ms`], ["Input", trace.usage.prompt_tokens], ["Output", trace.usage.completion_tokens], ["Cost", `$${trace.usage.estimated_cost_usd.toFixed(6)}`]].map(([label, value]) => <div key={label} className="min-w-0 rounded-xl bg-black/15 p-2"><p className="text-[8px] text-white/20">{label}</p><p className="mt-1 truncate text-[9px] text-white/50">{value}</p></div>)}</section>}
    </>}</div>
    {datasetOpen && <EvaluationDataset setId={setId} documentIds={documentIds} filters={filters} isFa={isFa} canManage={canManage} onClose={() => setDatasetOpen(false)} />}
    {comparisonOpen && <RetrieverComparison setId={setId} query={query} documentIds={documentIds} filters={filters} isFa={isFa} onClose={() => setComparisonOpen(false)} />}
  </aside></div>;
}
